"""add_meme_matches_and_tiktok_x_sources

Revision ID: e1e9fe1d53fe
Revises: a2f88b89b500
Create Date: 2026-06-29 08:55:04.672929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e9fe1d53fe'
down_revision: Union[str, Sequence[str], None] = 'a2f88b89b500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
